version: '2.2'

services:
  db:
    image: postgres:latest
    container_name: HelloChef-DB
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DATABASE: HelloChef-DB
    volumes:
      - postgres:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks: ['mynetwork']
  web:
    build: .
    container_name: HelloChef
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/HelloChef-Docker
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
    networks: ['mynetwork']
volumes:
  postgres:
networks: {mynetwork: {}}